server:
  port: ${port}
  tomcat:
    connectionTimeout: 300

springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    path: /swagger
    disable-swagger-default-url: true
    display-query-params-without-oauth2: true

api-prefix: /api

spring:
  datasource:
    url: ${database_url}
    username: ${database_name}
    password: ${database_pwd}
    driver-class-name: ${database_driver}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: ${database_dialect}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:80

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
    root: trace
    org.springframework.web: trace
    org.springframework.security: trace
    org.springframework.security.oauth2: trace