test2: testValue(local)
# local server port
port: 8080

# local database info
database_url: jdbc:h2:tcp://localhost/~/test;
database_name: sa

# sql log
show_sql: true

# swagger endpoint 제공 유무
api-docs-enabled: true

# swagger ui 제공 유무
swagger-ui-enabled: true