# Repo Action 페이지에 나타날 이름 
name: Spring Boot & Gradle CI/CD

# Event Trigger
# master branch에 push 또는 pull request가 발생할 경우 동작
# branch 단위 외에도, tag나 cron 식 등을 사용할 수 있음
on:
  push:
    branches: [ feature/30, develop, main ]
  pull_request:
    branches: [ develop, main ]

jobs:
  build:
    # 실행 환경 지정
    runs-on: ubuntu-latest

    # Task의 sequence를 명시한다.
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - uses: actions/checkout@v3
      - run: touch ./src/main/resources/env/prod.yml
      - run: echo "${{ secrets.PROD }}" > ./src/main/resources/env/prod.yml
      - run: cat ./src/main/resources/env/prod.yml

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew 

      # Build
      - name: Build with Gradle
        run: ./gradlew clean build -exclude-task test

      # 전송할 파일을 담을 디렉토리 생성
      - name: Make Directory for deliver
        run: mkdir deploy

      # Jar 파일 Copy
      - name: Copy Jar
        run: cp ./build/libs/*.jar ./deploy/

      # 압축파일 형태로 전달
      - name: Make zip file
        run: zip -r -qq -j ./battle-run-build.zip ./deploy

      # S3 Bucket으로 copy
      - name: Deliver to AWS S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 cp \
          --region ap-northeast-2 \
          --acl private \ 
          ./battle-run-build.zip s3://battle-run-build/
          
  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws deploy create-deployment \
          --application-name battle-run \
          --deployment-group-name battle-run-deploy-group \
          --profile prod
          --file-exists-behavior OVERWRITE \
          --s3-location bucket=battle-run-build,bundleType=zip,key=battle-run-build.zip \
          --region ap-northeast-2